#
# Profile for doing development work on full stack.
#
# Your changes will be visible live on browser reload or after restart:
#
# - Edit files in deployment/manager/
# - Edit files in keycloak/theme/
# - Mount the proxy-data volume in a new container and edit proxy configuration files
# - Change the proxy configuration to a directory mount and edit configuration files
#
version: '2.4'

volumes:
  proxy-data:
  postgresql-data:

services:

  manager:
    extends:
      file: deploy.yml
      service: manager
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      # Use local deployment data in host-mapped directory for easy development. The
      # ../deployment directory is the one which will be baked into the managers image.
      - ${DEPLOYMENT_DIRECTORY:-../deployment}:/deployment
      # Need to map GWT manager client into container when in dev mode
      - ../client:/opt/app/client
    environment:
      IDENTITY_NETWORK_WEBSERVER_PORT: 8080
      IDENTITY_NETWORK_SECURE: 'false'
      # Always wipe and enable dev optimizations
      DEV_MODE: 'true'
      # This switch can wipe all your Manager and Keycloak data, this is the factory reset!
      SETUP_WIPE_CLEAN_INSTALL: 'true'

  keycloak:
    extends:
      file: deploy.yml
      service: keycloak
    # Access directly if needed on localhost
    ports:
      - "8081:8080"
    volumes:
      - ../ui/keycloak/themes:/deployment/keycloak/themes
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    extends:
      file: deploy.yml
      service: postgresql
    # Access directly if needed on localhost
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data